server:
  port: 3001

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sea_db
    username: postgres
    password: 123456798
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
