--
-- PostgreSQL database dump
--

\restrict pZ2T2h4IX3mhJ1qmiP69vLcaCSs52orXofoDsV8ZWtyMMNOmdqgZa2yMcG3udwI

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: caja_chica_movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caja_chica_movimientos (
    id bigint NOT NULL,
    concepto character varying(255),
    monto numeric(15,2),
    tipo character varying(30),
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estatus character varying(30) DEFAULT 'Aprobado'::character varying
);


ALTER TABLE public.caja_chica_movimientos OWNER TO postgres;

--
-- Name: caja_chica_movimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caja_chica_movimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caja_chica_movimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caja_chica_parametros; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caja_chica_parametros (
    id bigint NOT NULL,
    fondo_fijo numeric(15,2) DEFAULT 0,
    monto_maximo_boleta numeric(15,2) DEFAULT 0,
    custodio character varying(150),
    estatus character varying(30) DEFAULT 'Activo'::character varying
);


ALTER TABLE public.caja_chica_parametros OWNER TO postgres;

--
-- Name: caja_chica_parametros_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caja_chica_parametros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caja_chica_parametros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: caja_chica_soportes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.caja_chica_soportes (
    id bigint NOT NULL,
    movimiento_id bigint,
    archivo character varying(255)
);


ALTER TABLE public.caja_chica_soportes OWNER TO postgres;

--
-- Name: caja_chica_soportes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.caja_chica_soportes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.caja_chica_soportes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: casos_comite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.casos_comite (
    id bigint NOT NULL,
    comite_id bigint,
    solicitud_id bigint,
    titulo character varying(200),
    descripcion text,
    estatus character varying(50) DEFAULT 'Pendiente'::character varying,
    decision text,
    fecha_presentacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.casos_comite OWNER TO postgres;

--
-- Name: casos_comite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.casos_comite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.casos_comite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: comites; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.comites (
    id bigint NOT NULL,
    codigo character varying(50),
    nombre character varying(150) NOT NULL,
    monto_max_aprob numeric(15,2),
    frecuencia character varying(50),
    estatus character varying(30) DEFAULT 'Activo'::character varying,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.comites OWNER TO postgres;

--
-- Name: comites_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.comites ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.comites_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: compania; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.compania (
    id bigint NOT NULL,
    rif character varying(20),
    razon_social character varying(150),
    direccion text,
    telefono character varying(30)
);


ALTER TABLE public.compania OWNER TO postgres;

--
-- Name: compania_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.compania ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.compania_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cxp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cxp (
    id bigint NOT NULL,
    factura character varying(50),
    numero_factura character varying(50),
    orden_compra_id bigint,
    oc_codigo character varying(50),
    recepcion_id bigint,
    proveedor_id bigint,
    proveedor character varying(150),
    emision date DEFAULT CURRENT_DATE,
    vencimiento date,
    subtotal numeric(15,2) DEFAULT 0,
    monto_iva numeric(15,2) DEFAULT 0,
    monto_islr_retenido numeric(15,2) DEFAULT 0,
    monto_neto numeric(15,2) DEFAULT 0,
    monto numeric(15,2) DEFAULT 0,
    estatus character varying(50) DEFAULT 'Pendiente'::character varying,
    moneda character varying(10) DEFAULT 'USD'::character varying,
    tasa_cambio numeric(15,4) DEFAULT 1.0,
    banco_pago character varying(100),
    motivo_devolucion text,
    fecha_emision timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.cxp OWNER TO postgres;

--
-- Name: cxp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cxp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cxp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentacion_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documentacion_proveedor (
    id bigint NOT NULL,
    proveedor_id bigint,
    nombre_documento character varying(150) NOT NULL,
    categoria character varying(100),
    nombre_archivo_pdf character varying(255) NOT NULL,
    peso_archivo character varying(30),
    fecha_carga timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_vencimiento date,
    estatus_validacion character varying(30) DEFAULT 'PENDIENTE'::character varying,
    origen_carga character varying(50) DEFAULT 'Portal Proveedores'::character varying
);


ALTER TABLE public.documentacion_proveedor OWNER TO postgres;

--
-- Name: documentacion_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.documentacion_proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentacion_proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: documentos_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.documentos_proveedor (
    id bigint NOT NULL,
    proveedor_id bigint,
    nombre_documento character varying(150) NOT NULL,
    categoria character varying(100),
    nombre_archivo_pdf character varying(255) NOT NULL,
    peso_archivo character varying(30),
    fecha_carga timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_vencimiento date,
    estatus_validacion character varying(30) DEFAULT 'PENDIENTE'::character varying,
    origen_carga character varying(50) DEFAULT 'Portal Proveedores'::character varying
);


ALTER TABLE public.documentos_proveedor OWNER TO postgres;

--
-- Name: documentos_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.documentos_proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.documentos_proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: evaluaciones_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.evaluaciones_proveedor (
    id bigint NOT NULL,
    proveedor_id bigint,
    puntaje numeric(5,2),
    comentario text,
    fecha_evaluacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.evaluaciones_proveedor OWNER TO postgres;

--
-- Name: evaluaciones_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.evaluaciones_proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.evaluaciones_proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: facturas_cxp; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.facturas_cxp (
    id bigint NOT NULL,
    numero_factura character varying(50) NOT NULL,
    orden_compra_id bigint,
    proveedor_id bigint,
    monto_factura numeric(15,2) NOT NULL,
    fecha_emision timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_vencimiento date,
    estatus_pago character varying(50) DEFAULT 'Aprobada para Pago'::character varying
);


ALTER TABLE public.facturas_cxp OWNER TO postgres;

--
-- Name: facturas_cxp_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.facturas_cxp ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.facturas_cxp_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: licitacion_ofertas; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.licitacion_ofertas (
    id bigint NOT NULL,
    licitacion_id bigint,
    proveedor_id bigint,
    precio_oferta numeric(15,2) NOT NULL,
    dias_entrega integer,
    puntaje_calidad numeric(5,2),
    garantia character varying(100),
    es_ganador integer DEFAULT 0
);


ALTER TABLE public.licitacion_ofertas OWNER TO postgres;

--
-- Name: licitacion_ofertas_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.licitacion_ofertas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.licitacion_ofertas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: licitaciones_seleccion; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.licitaciones_seleccion (
    id bigint NOT NULL,
    codigo_licitacion character varying(50) NOT NULL,
    solicitud_id bigint,
    proveedor_ganador_id bigint,
    monto_adjudicado numeric(15,2),
    estatus_contrato character varying(50) DEFAULT 'Pendiente Firma Proveedor'::character varying,
    contrato_firmado_pdf character varying(255),
    fecha_adjudicacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.licitaciones_seleccion OWNER TO postgres;

--
-- Name: licitaciones_seleccion_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.licitaciones_seleccion ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.licitaciones_seleccion_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: lista_valores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lista_valores (
    id bigint NOT NULL,
    lista character varying(50),
    codigo character varying(50),
    valor character varying(150)
);


ALTER TABLE public.lista_valores OWNER TO postgres;

--
-- Name: lista_valores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lista_valores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lista_valores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: logs_auditoria; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.logs_auditoria (
    id bigint NOT NULL,
    usuario character varying(100),
    accion character varying(255),
    detalle text,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.logs_auditoria OWNER TO postgres;

--
-- Name: logs_auditoria_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.logs_auditoria ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.logs_auditoria_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: miembros_comite; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.miembros_comite (
    id bigint NOT NULL,
    comite_id bigint,
    nombre character varying(150) NOT NULL,
    cargo character varying(100),
    cedula character varying(20),
    email character varying(100)
);


ALTER TABLE public.miembros_comite OWNER TO postgres;

--
-- Name: miembros_comite_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.miembros_comite ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.miembros_comite_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notificaciones_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notificaciones_proveedor (
    id bigint NOT NULL,
    proveedor_id bigint,
    titulo character varying(150),
    mensaje text,
    leido integer DEFAULT 0,
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.notificaciones_proveedor OWNER TO postgres;

--
-- Name: notificaciones_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notificaciones_proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notificaciones_proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordenes_compra; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ordenes_compra (
    id bigint NOT NULL,
    codigo character varying(50) NOT NULL,
    licitacion_id bigint,
    proveedor_id bigint,
    proveedor character varying(150),
    monto_total numeric(15,2) DEFAULT 0 NOT NULL,
    estatus_entrega character varying(50) DEFAULT 'En Proceso Almacén'::character varying,
    estatus character varying(50) DEFAULT 'Emitida'::character varying,
    fecha_emision timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.ordenes_compra OWNER TO postgres;

--
-- Name: ordenes_compra_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ordenes_compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordenes_compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ordenes_compra_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.ordenes_compra_items (
    id bigint NOT NULL,
    oc_id bigint,
    descripcion character varying(255),
    cantidad numeric(15,2),
    precio_unitario numeric(15,2),
    subtotal numeric(15,2)
);


ALTER TABLE public.ordenes_compra_items OWNER TO postgres;

--
-- Name: ordenes_compra_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.ordenes_compra_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ordenes_compra_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagos (
    id bigint NOT NULL,
    referencia character varying(50),
    referencia_pago character varying(50),
    cxp_id bigint,
    factura_id bigint,
    proveedor_id bigint,
    proveedor character varying(150),
    banco_origen character varying(100) DEFAULT 'Banco Mercantil'::character varying,
    cuenta_origen character varying(30),
    cuenta_destino character varying(30),
    monto numeric(15,2) NOT NULL,
    monto_liquidado numeric(15,2),
    fecha date DEFAULT CURRENT_DATE,
    estatus character varying(30) DEFAULT 'Procesado'::character varying
);


ALTER TABLE public.pagos OWNER TO postgres;

--
-- Name: pagos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pagos_liquidados; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pagos_liquidados (
    id bigint NOT NULL,
    referencia_pago character varying(50) NOT NULL,
    factura_id bigint,
    proveedor_id bigint,
    banco_origen character varying(100) DEFAULT 'Banco Mercantil'::character varying,
    cuenta_destino character varying(30) NOT NULL,
    monto_liquidado numeric(15,2) NOT NULL,
    fecha_pago timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estatus character varying(30) DEFAULT 'Procesado'::character varying
);


ALTER TABLE public.pagos_liquidados OWNER TO postgres;

--
-- Name: pagos_liquidados_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pagos_liquidados ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pagos_liquidados_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parametros_base; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.parametros_base (
    id bigint NOT NULL,
    clave character varying(100),
    valor text,
    descripcion character varying(255)
);


ALTER TABLE public.parametros_base OWNER TO postgres;

--
-- Name: parametros_base_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.parametros_base ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parametros_base_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: partidas_presupuestarias; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.partidas_presupuestarias (
    id bigint NOT NULL,
    codigo_partida character varying(50) NOT NULL,
    denominacion character varying(200) NOT NULL,
    centro_costo character varying(100) NOT NULL,
    limite_anual numeric(15,2) DEFAULT 0,
    saldo_disponible numeric(15,2) DEFAULT 0,
    estado character varying(20) DEFAULT 'ACTIVA'::character varying
);


ALTER TABLE public.partidas_presupuestarias OWNER TO postgres;

--
-- Name: partidas_presupuestarias_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.partidas_presupuestarias ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.partidas_presupuestarias_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: presupuesto_modificaciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.presupuesto_modificaciones (
    id bigint NOT NULL,
    codigo_modificacion character varying(50) NOT NULL,
    tipo_modificacion character varying(50) NOT NULL,
    partida_origen character varying(100),
    partida_destino character varying(100),
    monto numeric(15,2) NOT NULL,
    estatus_workflow character varying(50) DEFAULT 'Pendiente Finanzas'::character varying,
    fecha_solicitud timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.presupuesto_modificaciones OWNER TO postgres;

--
-- Name: presupuesto_modificaciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.presupuesto_modificaciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.presupuesto_modificaciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: presupuesto_trazabilidad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.presupuesto_trazabilidad (
    id bigint NOT NULL,
    partida_codigo character varying(50),
    precomprometido numeric(15,2) DEFAULT 0,
    comprometido numeric(15,2) DEFAULT 0,
    causado numeric(15,2) DEFAULT 0,
    pagado numeric(15,2) DEFAULT 0
);


ALTER TABLE public.presupuesto_trazabilidad OWNER TO postgres;

--
-- Name: presupuesto_trazabilidad_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.presupuesto_trazabilidad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.presupuesto_trazabilidad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: presupuestos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.presupuestos (
    id bigint NOT NULL,
    codigo_partida character varying(50) NOT NULL,
    denominacion character varying(200) NOT NULL,
    centro_costo character varying(100) NOT NULL,
    limite_anual numeric(15,2) DEFAULT 0,
    saldo_disponible numeric(15,2) DEFAULT 0,
    estado character varying(20) DEFAULT 'ACTIVA'::character varying
);


ALTER TABLE public.presupuestos OWNER TO postgres;

--
-- Name: presupuestos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.presupuestos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.presupuestos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: proveedores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.proveedores (
    id bigint NOT NULL,
    rif character varying(20) NOT NULL,
    nombre character varying(150) NOT NULL,
    categoria character varying(100),
    zona character varying(100),
    contacto character varying(100),
    telefono character varying(30),
    email character varying(100),
    banco character varying(100),
    cuenta_bancaria character varying(30),
    evaluacion numeric(5,2),
    estatus character varying(30) DEFAULT 'Activo'::character varying,
    fecha_ingreso date DEFAULT CURRENT_DATE,
    fecha_registro timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.proveedores OWNER TO postgres;

--
-- Name: proveedores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.proveedores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.proveedores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recepciones_almacen; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recepciones_almacen (
    id bigint NOT NULL,
    codigo character varying(50),
    oc_id bigint,
    oc_codigo character varying(50),
    proveedor character varying(150),
    fecha_recepcion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    estado character varying(50) DEFAULT 'Recibida'::character varying,
    notas text
);


ALTER TABLE public.recepciones_almacen OWNER TO postgres;

--
-- Name: recepciones_almacen_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recepciones_almacen ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recepciones_almacen_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: recepciones_almacen_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.recepciones_almacen_items (
    id bigint NOT NULL,
    recepcion_id bigint,
    descripcion character varying(255),
    cantidad_recibida numeric(15,2),
    estado_item character varying(50)
);


ALTER TABLE public.recepciones_almacen_items OWNER TO postgres;

--
-- Name: recepciones_almacen_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.recepciones_almacen_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recepciones_almacen_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: rendicion_gastos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rendicion_gastos (
    id bigint NOT NULL,
    viatico_id bigint,
    categoria character varying(100),
    monto numeric(15,2),
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.rendicion_gastos OWNER TO postgres;

--
-- Name: rendicion_gastos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rendicion_gastos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rendicion_gastos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: requerimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.requerimientos (
    id bigint NOT NULL,
    codigo character varying(50),
    tipo_orden character varying(50),
    solicitante character varying(100),
    departamento character varying(100),
    descripcion text,
    cantidad_unidad character varying(50),
    centro_costo character varying(100),
    prioridad character varying(30),
    etapa_negocio character varying(50) DEFAULT 'Solicitud'::character varying,
    estatus character varying(30) DEFAULT 'Pendiente'::character varying,
    monto_estimado numeric(15,2) DEFAULT 0,
    fecha_creacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.requerimientos OWNER TO postgres;

--
-- Name: requerimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.requerimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.requerimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: retenciones; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.retenciones (
    id bigint NOT NULL,
    cxp_id bigint,
    tipo_retencion character varying(50),
    porcentaje numeric(5,2),
    monto numeric(15,2),
    comprobante character varying(50),
    fecha timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.retenciones OWNER TO postgres;

--
-- Name: retenciones_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.retenciones ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.retenciones_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: roles; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roles (
    id bigint NOT NULL,
    nombre character varying(50),
    descripcion character varying(255)
);


ALTER TABLE public.roles OWNER TO postgres;

--
-- Name: roles_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.roles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.roles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitudes_compra; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.solicitudes_compra (
    id bigint NOT NULL,
    codigo_solicitud character varying(50) NOT NULL,
    partida_codigo character varying(50),
    departamento character varying(100) NOT NULL,
    solicitante character varying(100) NOT NULL,
    concepto character varying(255) NOT NULL,
    monto numeric(15,2) NOT NULL,
    estatus character varying(30) DEFAULT 'Pendiente'::character varying,
    fecha_solicitud timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public.solicitudes_compra OWNER TO postgres;

--
-- Name: solicitudes_compra_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.solicitudes_compra ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitudes_compra_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitudes_ingreso_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.solicitudes_ingreso_proveedor (
    id bigint NOT NULL,
    rif character varying(20) NOT NULL,
    proveedor character varying(150) NOT NULL,
    categoria character varying(100),
    email character varying(100) NOT NULL,
    telefono character varying(30),
    estatus character varying(30) DEFAULT 'Invitado'::character varying,
    token_invitacion character varying(100),
    banco_nombre character varying(100),
    cuenta_20_digitos character varying(30),
    titular_cuenta character varying(150),
    expediente_aprobado integer DEFAULT 0,
    fecha_invitacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_registro timestamp without time zone
);


ALTER TABLE public.solicitudes_ingreso_proveedor OWNER TO postgres;

--
-- Name: solicitudes_ingreso_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.solicitudes_ingreso_proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitudes_ingreso_proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: solicitudes_proveedor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.solicitudes_proveedor (
    id bigint NOT NULL,
    codigo character varying(50),
    proveedor_id bigint,
    proveedor character varying(150) NOT NULL,
    rif character varying(20) NOT NULL,
    contacto character varying(100),
    telefono character varying(30),
    email character varying(100),
    fecha date DEFAULT CURRENT_DATE,
    tipo character varying(50),
    etapa character varying(50),
    categoria character varying(100),
    estatus character varying(30) DEFAULT 'En revisión'::character varying,
    token_invitacion character varying(100),
    banco_nombre character varying(100),
    cuenta_20_digitos character varying(30),
    titular_cuenta character varying(150),
    expediente_aprobado integer DEFAULT 0,
    fecha_invitacion timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    fecha_registro timestamp without time zone
);


ALTER TABLE public.solicitudes_proveedor OWNER TO postgres;

--
-- Name: solicitudes_proveedor_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.solicitudes_proveedor ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.solicitudes_proveedor_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    username character varying(50),
    password character varying(255) NOT NULL,
    nombre character varying(100),
    email character varying(100),
    role_id bigint,
    estatus character varying(20) DEFAULT 'Activo'::character varying
);


ALTER TABLE public.usuarios OWNER TO postgres;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.usuarios ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viaticos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaticos (
    id bigint NOT NULL,
    solicitante character varying(150),
    destino character varying(150),
    motivo text,
    monto_asignado numeric(15,2),
    estatus character varying(50) DEFAULT 'Solicitado'::character varying,
    fecha_inicio date,
    fecha_fin date
);


ALTER TABLE public.viaticos OWNER TO postgres;

--
-- Name: viaticos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.viaticos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viaticos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viaticos_movimientos; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaticos_movimientos (
    id bigint NOT NULL,
    viatico_id bigint,
    concepto character varying(255),
    monto numeric(15,2),
    fecha date
);


ALTER TABLE public.viaticos_movimientos OWNER TO postgres;

--
-- Name: viaticos_movimientos_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.viaticos_movimientos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viaticos_movimientos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viaticos_parametros; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaticos_parametros (
    id bigint NOT NULL,
    tarifa_diaria numeric(15,2) DEFAULT 0,
    moneda character varying(10) DEFAULT 'USD'::character varying
);


ALTER TABLE public.viaticos_parametros OWNER TO postgres;

--
-- Name: viaticos_parametros_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.viaticos_parametros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viaticos_parametros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: viaticos_soportes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.viaticos_soportes (
    id bigint NOT NULL,
    viatico_id bigint,
    archivo character varying(255)
);


ALTER TABLE public.viaticos_soportes OWNER TO postgres;

--
-- Name: viaticos_soportes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.viaticos_soportes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.viaticos_soportes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: caja_chica_movimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caja_chica_movimientos (id, concepto, monto, tipo, fecha, estatus) FROM stdin;
1	CC-2026-052 - Apertura de fondo caja chica Operaciones	2500.00	Apertura	2026-08-15 23:01:22.139172	Aprobado
2	CC-2026-053 - Reposición gastos papelería y consumibles	980.00	Reposición	2026-08-15 23:01:22.139172	Aprobado
3	CC-2026-054 - Reposición fondo sucursal Valencia	640.00	Reposición	2026-08-15 23:01:22.139172	Aprobado
4	CC-2026-052 - Apertura de fondo caja chica Operaciones	2500.00	Apertura	2026-08-15 23:02:08.050963	Aprobado
5	CC-2026-053 - Reposición gastos papelería y consumibles	980.00	Reposición	2026-08-15 23:02:08.050963	Aprobado
6	CC-2026-054 - Reposición fondo sucursal Valencia	640.00	Reposición	2026-08-15 23:02:08.050963	Aprobado
7	Reposición Fondo Caja Chica	900.00	Reposición	2026-08-15 23:46:09.611781	Aprobado
8	Reposición Fondo Caja Chica	20.00	Reposición	2026-08-15 23:52:54.405102	Aprobado
\.


--
-- Data for Name: caja_chica_parametros; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caja_chica_parametros (id, fondo_fijo, monto_maximo_boleta, custodio, estatus) FROM stdin;
1	1500.00	200.00	A. Linares (Administración)	Activo
2	2500.00	300.00	R. Moreno (Operaciones Caracas)	Activo
3	1200.00	150.00	P. Gómez (Sucursal Valencia)	Activo
4	1500.00	200.00	A. Linares (Administración)	Activo
5	2500.00	300.00	R. Moreno (Operaciones Caracas)	Activo
6	1200.00	150.00	P. Gómez (Sucursal Valencia)	Activo
\.


--
-- Data for Name: caja_chica_soportes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.caja_chica_soportes (id, movimiento_id, archivo) FROM stdin;
1	1	Factura_Material_Limpieza_4421.pdf
2	2	Factura_Refrigerios_1187.pdf
3	3	Recibo_Mensajeria_008.pdf
4	1	Factura_Material_Limpieza_4421.pdf
5	2	Factura_Refrigerios_1187.pdf
6	3	Recibo_Mensajeria_008.pdf
\.


--
-- Data for Name: casos_comite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.casos_comite (id, comite_id, solicitud_id, titulo, descripcion, estatus, decision, fecha_presentacion) FROM stdin;
1	2	\N	CASO-2026-018	Adjudicación licitación compras mayores de servidores	Aprobado	Aprobado	2026-04-22 00:00:00
2	1	\N	CASO-2026-017	Compra urgente de repuestos de imprenta	Aprobado	Aprobado	2026-04-19 00:00:00
3	3	\N	CASO-2026-016	Proyecto renovación de data center principal	Diferido	Diferido	2026-04-15 00:00:00
4	4	\N	CASO-2026-015	Ampliación de infraestructura corporativa 2026	Aprobado	Aprobado	2026-04-10 00:00:00
5	2	\N	CASO-2026-018	Adjudicación licitación compras mayores de servidores	Aprobado	Aprobado	2026-04-22 00:00:00
6	1	\N	CASO-2026-017	Compra urgente de repuestos de imprenta	Aprobado	Aprobado	2026-04-19 00:00:00
7	3	\N	CASO-2026-016	Proyecto renovación de data center principal	Diferido	Diferido	2026-04-15 00:00:00
8	4	\N	CASO-2026-015	Ampliación de infraestructura corporativa 2026	Aprobado	Aprobado	2026-04-10 00:00:00
\.


--
-- Data for Name: comites; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.comites (id, codigo, nombre, monto_max_aprob, frecuencia, estatus, fecha_creacion) FROM stdin;
1	CM-01	Comité de Compras Menores	5000.00	Semanal	Activo	2026-08-15 23:01:22.130338
2	CM-02	Comité de Compras Mayores	50000.00	Quincenal	Activo	2026-08-15 23:01:22.130338
3	CM-03	Comité de Inversiones	250000.00	Mensual	Activo	2026-08-15 23:01:22.130338
4	CM-04	Comité Ejecutivo	1000000.00	Mensual	Activo	2026-08-15 23:01:22.130338
\.


--
-- Data for Name: compania; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.compania (id, rif, razon_social, direccion, telefono) FROM stdin;
1	J-31002233-4	Consultores 2026 C.A.	Av. Francisco de Miranda, Torre SEA, Piso 8, Caracas	+58 212-555-2026
2	J-31002233-5	Consultores 2026 - Filial Andes	Av. Las Américas, Centro Empresarial Mérida	+58 274-555-1010
3	J-31002233-4	Consultores 2026 C.A.	Av. Francisco de Miranda, Torre SEA, Piso 8, Caracas	+58 212-555-2026
4	J-31002233-5	Consultores 2026 - Filial Andes	Av. Las Américas, Centro Empresarial Mérida	+58 274-555-1010
\.


--
-- Data for Name: cxp; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cxp (id, factura, numero_factura, orden_compra_id, oc_codigo, recepcion_id, proveedor_id, proveedor, emision, vencimiento, subtotal, monto_iva, monto_islr_retenido, monto_neto, monto, estatus, moneda, tasa_cambio, banco_pago, motivo_devolucion, fecha_emision) FROM stdin;
1	FAC-001-998	\N	\N	\N	\N	\N	Distribuidora Andina C.A.	2026-08-15	2026-08-25	5000.00	800.00	0.00	5800.00	5800.00	Pendiente	USD	1.0000	\N	\N	2026-08-15 22:48:51.121283
2	F-00012458	\N	\N	\N	\N	\N	Distribuidora Andina C.A.	2026-04-02	2026-05-02	12450.00	1992.00	0.00	14442.00	12450.00	Pendiente	USD	1.0000	\N	\N	2026-08-15 23:01:22.13617
3	F-00012450	\N	\N	\N	\N	\N	Tecnología Global S.A.	2026-04-04	2026-05-04	8900.00	1424.00	0.00	10324.00	8900.00	Pendiente	USD	1.0000	\N	\N	2026-08-15 23:01:22.13617
4	F-00012431	\N	\N	\N	\N	\N	Servicios Integrales 360	2026-04-07	2026-05-07	5230.00	836.80	0.00	6066.80	5230.00	Pendiente	USD	1.0000	\N	\N	2026-08-15 23:01:22.13617
5	F-00012410	\N	\N	\N	\N	\N	Logística Caribe	2026-04-10	2026-05-10	17800.00	2848.00	0.00	20648.00	17800.00	Pendiente	USD	1.0000	\N	\N	2026-08-15 23:01:22.13617
6	F-00012380	\N	\N	\N	\N	\N	Suministros Pro	2026-03-12	2026-04-12	3120.00	499.20	0.00	3619.20	3120.00	Vencida	USD	1.0000	\N	\N	2026-08-15 23:01:22.13617
\.


--
-- Data for Name: documentacion_proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.documentacion_proveedor (id, proveedor_id, nombre_documento, categoria, nombre_archivo_pdf, peso_archivo, fecha_carga, fecha_vencimiento, estatus_validacion, origen_carga) FROM stdin;
4	1	RIF Actualizado 2026	Legal	RIF_Andina_2026.pdf	1.2 MB	2026-08-15 23:02:08.045679	2026-12-31	Vigente	Portal Proveedores
5	4	Solvencia Laboral INCES	Laboral	Solvencia_Laboral_TecGob.pdf	850 KB	2026-08-15 23:02:08.045679	2026-06-15	Por vencer	Portal Proveedores
6	5	Póliza Responsabilidad Civil	Seguros	Poliza_RC_Serv360.pdf	2.4 MB	2026-08-15 23:02:08.045679	2026-03-30	Vencido	Portal Proveedores
\.


--
-- Data for Name: documentos_proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.documentos_proveedor (id, proveedor_id, nombre_documento, categoria, nombre_archivo_pdf, peso_archivo, fecha_carga, fecha_vencimiento, estatus_validacion, origen_carga) FROM stdin;
\.


--
-- Data for Name: evaluaciones_proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.evaluaciones_proveedor (id, proveedor_id, puntaje, comentario, fecha_evaluacion) FROM stdin;
5	1	91.70	Excelente cumplimiento de tiempos en entrega de insumos Q1 2026	2026-08-15 23:02:08.043438
6	4	90.60	Alta calidad de equipamiento hardware y garantías de soporte	2026-08-15 23:02:08.043438
7	5	84.00	Servicios de mantenimiento satisfactorios con observaciones en tiempos	2026-08-15 23:02:08.043438
8	6	89.00	Excelente servicio de transporte y logística nacional	2026-08-15 23:02:08.043438
\.


--
-- Data for Name: facturas_cxp; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.facturas_cxp (id, numero_factura, orden_compra_id, proveedor_id, monto_factura, fecha_emision, fecha_vencimiento, estatus_pago) FROM stdin;
\.


--
-- Data for Name: licitacion_ofertas; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.licitacion_ofertas (id, licitacion_id, proveedor_id, precio_oferta, dias_entrega, puntaje_calidad, garantia, es_ganador) FROM stdin;
\.


--
-- Data for Name: licitaciones_seleccion; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.licitaciones_seleccion (id, codigo_licitacion, solicitud_id, proveedor_ganador_id, monto_adjudicado, estatus_contrato, contrato_firmado_pdf, fecha_adjudicacion) FROM stdin;
\.


--
-- Data for Name: lista_valores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.lista_valores (id, lista, codigo, valor) FROM stdin;
1	Tipos de documento	LV-001	RIF, Cédula, Pasaporte, Registro Mercantil
2	Formas de pago	LV-002	Transferencia, Cheque, Pago Móvil, Carta de Crédito
3	Categorías de proveedor	LV-003	Insumos, Hardware/SW, Mantenimiento, Transporte, Servicios
4	Tipos de documento	LV-001	RIF, Cédula, Pasaporte, Registro Mercantil
5	Formas de pago	LV-002	Transferencia, Cheque, Pago Móvil, Carta de Crédito
6	Categorías de proveedor	LV-003	Insumos, Hardware/SW, Mantenimiento, Transporte, Servicios
\.


--
-- Data for Name: logs_auditoria; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.logs_auditoria (id, usuario, accion, detalle, fecha) FROM stdin;
1	mperez	Aprobó pago PAG-2026-0312	Pago a Suministros Pro procesado por $3,120	2026-08-15 23:01:22.151755
2	csalazar	Creó OC-2026-0188	Orden de compra emitida a Distribuidora Andina	2026-08-15 23:01:22.151755
3	alinares	Aprobó solicitud SOL-2026-0032	Proveedor Aseo Total promovido a alta SEA	2026-08-15 23:01:22.151755
4	mperez	Aprobó pago PAG-2026-0312	Pago a Suministros Pro procesado por $3,120	2026-08-15 23:02:08.057073
5	csalazar	Creó OC-2026-0188	Orden de compra emitida a Distribuidora Andina	2026-08-15 23:02:08.057073
6	alinares	Aprobó solicitud SOL-2026-0032	Proveedor Aseo Total promovido a alta SEA	2026-08-15 23:02:08.057073
\.


--
-- Data for Name: miembros_comite; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.miembros_comite (id, comite_id, nombre, cargo, cedula, email) FROM stdin;
1	1	Andrea Linares	Jefe de Compras	V-15.221.009	alinares@sea.gob.ve
2	2	María Pérez	Gerente Finanzas	V-12.345.678	mperez@sea.gob.ve
3	3	Rafael Moreno	Gerente IT	V-13.554.221	rmoreno@sea.gob.ve
4	4	Carlos Salazar	Director General	V-9.876.543	csalazar@sea.gob.ve
5	1	Andrea Linares	Jefe de Compras	V-15.221.009	alinares@sea.gob.ve
6	2	María Pérez	Gerente Finanzas	V-12.345.678	mperez@sea.gob.ve
7	3	Rafael Moreno	Gerente IT	V-13.554.221	rmoreno@sea.gob.ve
8	4	Carlos Salazar	Director General	V-9.876.543	csalazar@sea.gob.ve
\.


--
-- Data for Name: notificaciones_proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notificaciones_proveedor (id, proveedor_id, titulo, mensaje, leido, fecha) FROM stdin;
1	\N	NOT-1042	Carta de referencia comercial emitida para Distribuidora Andina C.A.	1	2026-08-10 23:01:22.127573
2	\N	NOT-1041	Selección por servicio adjudicado a Logística Caribe	1	2026-08-08 23:01:22.127573
3	\N	NOT-1040	Observaciones de documentación recibidas para Suministros Pro	0	2026-08-05 23:01:22.127573
4	\N	NOT-1042	Carta de referencia comercial emitida para Distribuidora Andina C.A.	1	2026-08-10 23:02:08.045063
5	\N	NOT-1041	Selección por servicio adjudicado a Logística Caribe	1	2026-08-08 23:02:08.045063
6	\N	NOT-1040	Observaciones de documentación recibidas para Suministros Pro	0	2026-08-05 23:02:08.045063
\.


--
-- Data for Name: ordenes_compra; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ordenes_compra (id, codigo, licitacion_id, proveedor_id, proveedor, monto_total, estatus_entrega, estatus, fecha_emision) FROM stdin;
1	OC-2026-0188	\N	1	Distribuidora Andina C.A.	12450.00	Recibido Total	Emitida	2026-08-15 23:01:22.134191
2	OC-2026-0187	\N	2	Tecnología Global S.A.	8900.00	En Proceso Almacén	Emitida	2026-08-15 23:01:22.134191
3	OC-2026-0186	\N	4	Logística Caribe	17800.00	Pendiente Entrega	Emitida	2026-08-15 23:01:22.134191
\.


--
-- Data for Name: ordenes_compra_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.ordenes_compra_items (id, oc_id, descripcion, cantidad, precio_unitario, subtotal) FROM stdin;
\.


--
-- Data for Name: pagos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pagos (id, referencia, referencia_pago, cxp_id, factura_id, proveedor_id, proveedor, banco_origen, cuenta_origen, cuenta_destino, monto, monto_liquidado, fecha, estatus) FROM stdin;
1	PAG-2026-001	\N	\N	\N	\N	Distribuidora Andina C.A.	Banco Mercantil	0105-0012-34-10009012	0105-0012-34-10009012	2500.00	\N	2026-08-15	Procesado
2	PAG-2026-0312	\N	\N	\N	\N	Suministros Pro	Banco Mercantil	0105-0012-34-10009012	0172-0001-99-40001234	3120.00	\N	2026-04-22	Procesado
3	PAG-2026-0311	\N	\N	\N	\N	Logística Caribe	Banco Mercantil	0105-0012-34-10009012	0102-0444-55-10008822	17800.00	\N	2026-04-20	Procesado
4	PAG-2026-0310	\N	\N	\N	\N	Tecnología Global S.A.	Banesco	0134-0099-88-20004511	0134-0099-88-20004511	8900.00	\N	2026-04-18	En tránsito
\.


--
-- Data for Name: pagos_liquidados; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pagos_liquidados (id, referencia_pago, factura_id, proveedor_id, banco_origen, cuenta_destino, monto_liquidado, fecha_pago, estatus) FROM stdin;
\.


--
-- Data for Name: parametros_base; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.parametros_base (id, clave, valor, descripcion) FROM stdin;
1	PAISES	45	Países configurados
2	CIUDADES	312	Ciudades configuradas
3	BANCOS	38	Bancos nacionales e internacionales
4	MONEDAS	14	Monedas activas
\.


--
-- Data for Name: partidas_presupuestarias; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.partidas_presupuestarias (id, codigo_partida, denominacion, centro_costo, limite_anual, saldo_disponible, estado) FROM stdin;
1	PART-401.01.02	Equipos de Computación e Infraestructura	IT Planta	250000.00	181000.00	ACTIVA
2	PART-401.02.05	Licenciamiento de Software y Base de Datos	IT Corporativo	180000.00	106100.00	ACTIVA
3	PART-402.01.01	Materiales y Suministros de Oficina	Administración	45000.00	21000.00	ACTIVA
\.


--
-- Data for Name: presupuesto_modificaciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.presupuesto_modificaciones (id, codigo_modificacion, tipo_modificacion, partida_origen, partida_destino, monto, estatus_workflow, fecha_solicitud) FROM stdin;
\.


--
-- Data for Name: presupuesto_trazabilidad; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.presupuesto_trazabilidad (id, partida_codigo, precomprometido, comprometido, causado, pagado) FROM stdin;
\.


--
-- Data for Name: presupuestos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.presupuestos (id, codigo_partida, denominacion, centro_costo, limite_anual, saldo_disponible, estado) FROM stdin;
1	PART-401.01.02	Equipos de Computación e Infraestructura	IT Planta	250000.00	181000.00	ACTIVA
2	PART-401.02.05	Licenciamiento de Software y Base de Datos	IT Corporativo	180000.00	106100.00	ACTIVA
3	PART-402.01.01	Materiales y Suministros de Oficina	Administración	45000.00	21000.00	ACTIVA
\.


--
-- Data for Name: proveedores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.proveedores (id, rif, nombre, categoria, zona, contacto, telefono, email, banco, cuenta_bancaria, evaluacion, estatus, fecha_ingreso, fecha_registro) FROM stdin;
2	J-40987654-3	Tecnología Global S.A.	Tecnología	Centro	María Rodríguez	+58 412 9876543	ventas@tecglobal.com	Banesco	0134-0099-88-20004511	\N	Activo	2026-08-15	2026-08-15 22:48:51.11659
1	J-30123456-7	Distribuidora Andina C.A.	Tecnología	Gran Caracas	Carlos Mendoza	+58 414 1234567	contacto@andina.com	Banco Mercantil	0105-0012-34-10009012	\N	Activo	2026-08-15	2026-08-15 22:48:51.113386
4	J-31998877-2	Tecnología Global S.A.	Hardware/SW	Nacional	L. Ramírez	+58 212-555-0144	ventas@tecglobal.com	Banesco	0134-0099-88-20004511	90.60	Activo	2026-08-15	2026-08-15 23:01:22.108271
5	J-30551122-9	Servicios Integrales 360	Mantenimiento	Centro	C. Salazar	+58 414-555-0188	contacto@servicios360.com	BBVA Provincial	0108-0111-22-30009911	84.00	Activo	2026-08-15	2026-08-15 23:01:22.108271
6	J-32004411-0	Logística Caribe	Transporte	Costa	R. Moreno	+58 261-555-0203	logistica@caribe.com	Banco de Venezuela	0102-0444-55-10008822	89.00	Activo	2026-08-15	2026-08-15 23:01:22.108271
7	J-29887766-4	Suministros Pro	Oficina	Caracas	A. Linares	+58 212-555-0111	ventas@suministrospro.com	Bancamiga	0172-0001-99-40001234	75.00	Inactivo	2026-08-15	2026-08-15 23:01:22.108271
8	J-31112233-5	Construcciones Vega	Obras	Andes	J. Vega	+58 274-555-0167	info@vega.com	Banco Exterior	0115-0033-11-20005566	82.00	Activo	2026-08-15	2026-08-15 23:01:22.108271
\.


--
-- Data for Name: recepciones_almacen; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recepciones_almacen (id, codigo, oc_id, oc_codigo, proveedor, fecha_recepcion, estado, notas) FROM stdin;
1	REC-2026-0045	\N	OC-2026-0188	Distribuidora Andina C.A.	2026-08-15 23:01:22.135211	Recibida Conforme	Equipos recibidos y probados en almacén central
2	REC-2026-0044	\N	OC-2026-0187	Tecnología Global S.A.	2026-08-15 23:01:22.135211	En Revisión	Lote de toners inspeccionándose
\.


--
-- Data for Name: recepciones_almacen_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.recepciones_almacen_items (id, recepcion_id, descripcion, cantidad_recibida, estado_item) FROM stdin;
\.


--
-- Data for Name: rendicion_gastos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.rendicion_gastos (id, viatico_id, categoria, monto, fecha) FROM stdin;
1	3	Hospedaje	110.00	2026-08-15 23:01:22.146518
2	3	Transporte	35.00	2026-08-15 23:01:22.146518
3	3	Hospedaje	110.00	2026-08-15 23:02:08.05521
4	3	Transporte	35.00	2026-08-15 23:02:08.05521
\.


--
-- Data for Name: requerimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.requerimientos (id, codigo, tipo_orden, solicitante, departamento, descripcion, cantidad_unidad, centro_costo, prioridad, etapa_negocio, estatus, monto_estimado, fecha_creacion) FROM stdin;
1	REQ-2026-001	Compra Directa	Juan Pérez	IT Planta	Laptops Servidores y Switche	5 Unidades	IT Planta	Alta	Solicitud	Pendiente	12500.00	2026-08-15 22:48:51.120444
2	SOL-2026-091	Producto	Juan Pérez	IT Planta	Renovación licencias antivirus (Bitdefender 2026)	50 licencias	IT Planta	Urgente	Solicitud	ENVIADA	12500.00	2026-08-15 23:01:22.133539
3	SOL-2026-090	Servicio	María García	Operaciones	Repuestos planta Caracas (Filtros y Correas)	12 unidades	Mantenimiento Planta	Normal	Presupuesto	APROBADA	8500.00	2026-08-15 23:01:22.133539
4	SOL-2026-089	Producto	Carlos Rodríguez	Administración	Insumos oficina Q2 (Papelería y Toners)	1 lote global	Gastos Administrativos	Programada	Aprobación	BORRADOR	3200.00	2026-08-15 23:01:22.133539
5	SOL-2026-088	Servicio	Ana López	Ventas	Material POP para feria comercial	500 unidades	Marketing y Ventas	Urgente	Recepción	EN PROCESO	4500.00	2026-08-15 23:01:22.133539
6	SOL-2026-087	Producto	Luis Rivas	Logística	Cámara Profesional para Marketing	1 unidad	Marketing	Urgente	Compras	APROBADA	1800.00	2026-08-15 23:01:22.133539
12	SOL-2026-6144	Producto	Isaac Lovera	Administración	Prueba	5	Administración	Normal	Recepción	Pendiente	100.00	2026-08-15 23:27:06.535825
\.


--
-- Data for Name: retenciones; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.retenciones (id, cxp_id, tipo_retencion, porcentaje, monto, comprobante, fecha) FROM stdin;
1	1	IVA 75%	75.00	1494.00	RET-IVA-00891	2026-08-15 23:01:22.13673
2	2	IVA 75%	75.00	1068.00	RET-IVA-00890	2026-08-15 23:01:22.13673
3	3	ISLR 2%	2.00	105.00	RET-ISLR-00342	2026-08-15 23:01:22.13673
4	1	IVA 75%	75.00	1494.00	RET-IVA-00891	2026-08-15 23:02:08.049588
5	2	IVA 75%	75.00	1068.00	RET-IVA-00890	2026-08-15 23:02:08.049588
6	3	ISLR 2%	2.00	105.00	RET-ISLR-00342	2026-08-15 23:02:08.049588
\.


--
-- Data for Name: roles; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.roles (id, nombre, descripcion) FROM stdin;
1	Administrador	Acceso total al sistema
2	Director	Aprobaciones de comités e inversiones
3	Compras	Gestión de requerimientos y proveedores
4	Tesorería	Gestión de pagos, CxP, caja chica y viáticos
\.


--
-- Data for Name: solicitudes_compra; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.solicitudes_compra (id, codigo_solicitud, partida_codigo, departamento, solicitante, concepto, monto, estatus, fecha_solicitud) FROM stdin;
\.


--
-- Data for Name: solicitudes_ingreso_proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.solicitudes_ingreso_proveedor (id, rif, proveedor, categoria, email, telefono, estatus, token_invitacion, banco_nombre, cuenta_20_digitos, titular_cuenta, expediente_aprobado, fecha_invitacion, fecha_registro) FROM stdin;
\.


--
-- Data for Name: solicitudes_proveedor; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.solicitudes_proveedor (id, codigo, proveedor_id, proveedor, rif, contacto, telefono, email, fecha, tipo, etapa, categoria, estatus, token_invitacion, banco_nombre, cuenta_20_digitos, titular_cuenta, expediente_aprobado, fecha_invitacion, fecha_registro) FROM stdin;
1	SOL-2026-0036	\N	Innovatech C.A.	J-40112233-9	D. Herrera	+58 412-555-0999	info@innovatech.com	2026-04-25	Nuevo registro	Registro	Tecnología	Pendiente	\N	\N	\N	\N	0	2026-08-15 23:01:22.116523	\N
2	SOL-2026-0035	\N	Distribuidora Sol	J-40556677-1	G. Torres	+58 414-555-0888	ventas@distribuidorasol.com	2026-04-24	Nuevo registro	Documentación	Insumos	Pendiente	\N	\N	\N	\N	0	2026-08-15 23:01:22.116523	\N
3	SOL-2026-0034	\N	Imprenta Nacional	J-30998811-5	F. Blanco	+58 212-555-0777	contacto@imprenta.gob.ve	2026-04-22	Actualización	Validación Legal	Servicios	En revisión	\N	\N	\N	\N	0	2026-08-15 23:01:22.116523	\N
4	SOL-2026-0033	\N	Servitec del Sur	J-31445566-2	H. Medina	+58 261-555-0666	contacto@servitec.com	2026-04-20	Nuevo registro	Aprobación	Mantenimiento	Pendiente	\N	\N	\N	\N	0	2026-08-15 23:01:22.116523	\N
5	SOL-2026-0032	\N	Aseo Total S.A.	J-30221144-8	E. Castillo	+58 212-555-0555	contacto@aseototal.com	2026-04-18	Nuevo registro	Alta en SEA	Servicios	Aprobado	\N	\N	\N	\N	0	2026-08-15 23:01:22.116523	\N
6	SOL-2026-0031	\N	Cargo Express	J-40889900-3	K. Rojas	+58 241-555-0444	envios@cargoexpress.com	2026-04-15	Nuevo registro	Validación Legal	Transporte	Rechazado	\N	\N	\N	\N	0	2026-08-15 23:01:22.116523	\N
7	SOL-2026-0036	\N	Innovatech C.A.	J-40112233-9	D. Herrera	+58 412-555-0999	info@innovatech.com	2026-04-25	Nuevo registro	Registro	Tecnología	Pendiente	\N	\N	\N	\N	0	2026-08-15 23:02:08.042455	\N
8	SOL-2026-0035	\N	Distribuidora Sol	J-40556677-1	G. Torres	+58 414-555-0888	ventas@distribuidorasol.com	2026-04-24	Nuevo registro	Documentación	Insumos	Pendiente	\N	\N	\N	\N	0	2026-08-15 23:02:08.042455	\N
9	SOL-2026-0034	\N	Imprenta Nacional	J-30998811-5	F. Blanco	+58 212-555-0777	contacto@imprenta.gob.ve	2026-04-22	Actualización	Validación Legal	Servicios	En revisión	\N	\N	\N	\N	0	2026-08-15 23:02:08.042455	\N
10	SOL-2026-0033	\N	Servitec del Sur	J-31445566-2	H. Medina	+58 261-555-0666	contacto@servitec.com	2026-04-20	Nuevo registro	Aprobación	Mantenimiento	Pendiente	\N	\N	\N	\N	0	2026-08-15 23:02:08.042455	\N
11	SOL-2026-0032	\N	Aseo Total S.A.	J-30221144-8	E. Castillo	+58 212-555-0555	contacto@aseototal.com	2026-04-18	Nuevo registro	Alta en SEA	Servicios	Aprobado	\N	\N	\N	\N	0	2026-08-15 23:02:08.042455	\N
12	SOL-2026-0031	\N	Cargo Express	J-40889900-3	K. Rojas	+58 241-555-0444	envios@cargoexpress.com	2026-04-15	Nuevo registro	Aprobación	Transporte	Rechazado	\N	\N	\N	\N	0	2026-08-15 23:02:08.042455	\N
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.usuarios (id, username, password, nombre, email, role_id, estatus) FROM stdin;
1	admin	123456798	Administrador SEA	admin@sea.gob.ve	1	Activo
2	mperez	123456798	María Pérez	mperez@sea.gob.ve	2	Activo
3	csalazar	123456798	Carlos Salazar	csalazar@sea.gob.ve	2	Activo
4	alinares	123456798	Andrea Linares	alinares@sea.gob.ve	3	Activo
\.


--
-- Data for Name: viaticos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.viaticos (id, solicitante, destino, motivo, monto_asignado, estatus, fecha_inicio, fecha_fin) FROM stdin;
1	M. Pérez	Maracaibo	Inspección técnica de planta occidental	1240.00	Aprobado	2026-05-04	2026-05-07
2	C. Salazar	Bogotá	Reunión estratégica filial regional	2980.00	En revisión	2026-05-12	2026-05-15
3	L. Ramírez	Valencia	Supervisión instalación de sistemas	380.00	Pagado	2026-04-28	2026-04-29
5	M. Pérez	Maracaibo	Inspección técnica de planta occidental	1240.00	Aprobado	2026-05-04	2026-05-07
6	C. Salazar	Bogotá	Reunión estratégica filial regional	2980.00	En revisión	2026-05-12	2026-05-15
7	L. Ramírez	Valencia	Supervisión instalación de sistemas	380.00	Pagado	2026-04-28	2026-04-29
8	J. Fernandez	Caracas	Jornada de capacitación central	850.00	Pendiente	2026-05-11	2026-05-14
4	J. Fernandez	Merida	Jornada de capacitación central	950.00	En revision	2026-05-11	2026-05-14
9	R. Gomez	Puerto La Cruz	Inspeccion de oficina	1150.00	Pendiente	\N	\N
10	A. Medina	Barquisimeto	Auditoria de planta	780.00	Pendiente	\N	\N
11	José Fernández	Maracay	Asignación de viaje	1500.00	Aprobación	\N	\N
\.


--
-- Data for Name: viaticos_movimientos; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.viaticos_movimientos (id, viatico_id, concepto, monto, fecha) FROM stdin;
1	1	MV-001 - Asignación viático Maracaibo	1240.00	2026-04-22
2	2	MV-002 - Replanificación agenda Bogotá	0.00	2026-04-23
3	3	MV-003 - Ajuste de rendición Valencia	-40.00	2026-04-20
4	1	MV-001 - Asignación viático Maracaibo	1240.00	2026-04-22
5	2	MV-002 - Replanificación agenda Bogotá	0.00	2026-04-23
6	3	MV-003 - Ajuste de rendición Valencia	-40.00	2026-04-20
\.


--
-- Data for Name: viaticos_parametros; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.viaticos_parametros (id, tarifa_diaria, moneda) FROM stdin;
1	280.00	USD
2	220.00	USD
3	110.00	USD
4	80.00	USD
5	280.00	USD
6	220.00	USD
7	110.00	USD
8	80.00	USD
\.


--
-- Data for Name: viaticos_soportes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.viaticos_soportes (id, viatico_id, archivo) FROM stdin;
1	3	VS-441 - Factura_Hotel_Hesperia_441.pdf
2	3	VS-442 - Recibo_Taxi_Aeropuerto_442.pdf
3	3	VS-441 - Factura_Hotel_Hesperia_441.pdf
4	3	VS-442 - Recibo_Taxi_Aeropuerto_442.pdf
\.


--
-- Name: caja_chica_movimientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caja_chica_movimientos_id_seq', 8, true);


--
-- Name: caja_chica_parametros_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caja_chica_parametros_id_seq', 6, true);


--
-- Name: caja_chica_soportes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.caja_chica_soportes_id_seq', 6, true);


--
-- Name: casos_comite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.casos_comite_id_seq', 8, true);


--
-- Name: comites_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.comites_id_seq', 8, true);


--
-- Name: compania_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.compania_id_seq', 4, true);


--
-- Name: cxp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cxp_id_seq', 11, true);


--
-- Name: documentacion_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.documentacion_proveedor_id_seq', 6, true);


--
-- Name: documentos_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.documentos_proveedor_id_seq', 1, false);


--
-- Name: evaluaciones_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.evaluaciones_proveedor_id_seq', 8, true);


--
-- Name: facturas_cxp_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.facturas_cxp_id_seq', 1, false);


--
-- Name: licitacion_ofertas_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.licitacion_ofertas_id_seq', 1, false);


--
-- Name: licitaciones_seleccion_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.licitaciones_seleccion_id_seq', 1, false);


--
-- Name: lista_valores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.lista_valores_id_seq', 6, true);


--
-- Name: logs_auditoria_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.logs_auditoria_id_seq', 6, true);


--
-- Name: miembros_comite_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.miembros_comite_id_seq', 8, true);


--
-- Name: notificaciones_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notificaciones_proveedor_id_seq', 6, true);


--
-- Name: ordenes_compra_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ordenes_compra_id_seq', 6, true);


--
-- Name: ordenes_compra_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.ordenes_compra_items_id_seq', 1, false);


--
-- Name: pagos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pagos_id_seq', 7, true);


--
-- Name: pagos_liquidados_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pagos_liquidados_id_seq', 1, false);


--
-- Name: parametros_base_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.parametros_base_id_seq', 8, true);


--
-- Name: partidas_presupuestarias_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.partidas_presupuestarias_id_seq', 3, true);


--
-- Name: presupuesto_modificaciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.presupuesto_modificaciones_id_seq', 1, false);


--
-- Name: presupuesto_trazabilidad_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.presupuesto_trazabilidad_id_seq', 1, false);


--
-- Name: presupuestos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.presupuestos_id_seq', 3, true);


--
-- Name: proveedores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.proveedores_id_seq', 14, true);


--
-- Name: recepciones_almacen_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recepciones_almacen_id_seq', 4, true);


--
-- Name: recepciones_almacen_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.recepciones_almacen_items_id_seq', 1, false);


--
-- Name: rendicion_gastos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.rendicion_gastos_id_seq', 4, true);


--
-- Name: requerimientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.requerimientos_id_seq', 12, true);


--
-- Name: retenciones_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.retenciones_id_seq', 6, true);


--
-- Name: roles_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.roles_id_seq', 8, true);


--
-- Name: solicitudes_compra_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.solicitudes_compra_id_seq', 1, false);


--
-- Name: solicitudes_ingreso_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.solicitudes_ingreso_proveedor_id_seq', 1, false);


--
-- Name: solicitudes_proveedor_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.solicitudes_proveedor_id_seq', 12, true);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 8, true);


--
-- Name: viaticos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.viaticos_id_seq', 11, true);


--
-- Name: viaticos_movimientos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.viaticos_movimientos_id_seq', 6, true);


--
-- Name: viaticos_parametros_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.viaticos_parametros_id_seq', 8, true);


--
-- Name: viaticos_soportes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.viaticos_soportes_id_seq', 4, true);


--
-- Name: caja_chica_movimientos caja_chica_movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_chica_movimientos
    ADD CONSTRAINT caja_chica_movimientos_pkey PRIMARY KEY (id);


--
-- Name: caja_chica_parametros caja_chica_parametros_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_chica_parametros
    ADD CONSTRAINT caja_chica_parametros_pkey PRIMARY KEY (id);


--
-- Name: caja_chica_soportes caja_chica_soportes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_chica_soportes
    ADD CONSTRAINT caja_chica_soportes_pkey PRIMARY KEY (id);


--
-- Name: casos_comite casos_comite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.casos_comite
    ADD CONSTRAINT casos_comite_pkey PRIMARY KEY (id);


--
-- Name: comites comites_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comites
    ADD CONSTRAINT comites_codigo_key UNIQUE (codigo);


--
-- Name: comites comites_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.comites
    ADD CONSTRAINT comites_pkey PRIMARY KEY (id);


--
-- Name: compania compania_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.compania
    ADD CONSTRAINT compania_pkey PRIMARY KEY (id);


--
-- Name: cxp cxp_factura_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cxp
    ADD CONSTRAINT cxp_factura_key UNIQUE (factura);


--
-- Name: cxp cxp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cxp
    ADD CONSTRAINT cxp_pkey PRIMARY KEY (id);


--
-- Name: documentacion_proveedor documentacion_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentacion_proveedor
    ADD CONSTRAINT documentacion_proveedor_pkey PRIMARY KEY (id);


--
-- Name: documentos_proveedor documentos_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos_proveedor
    ADD CONSTRAINT documentos_proveedor_pkey PRIMARY KEY (id);


--
-- Name: evaluaciones_proveedor evaluaciones_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluaciones_proveedor
    ADD CONSTRAINT evaluaciones_proveedor_pkey PRIMARY KEY (id);


--
-- Name: facturas_cxp facturas_cxp_numero_factura_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas_cxp
    ADD CONSTRAINT facturas_cxp_numero_factura_key UNIQUE (numero_factura);


--
-- Name: facturas_cxp facturas_cxp_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas_cxp
    ADD CONSTRAINT facturas_cxp_pkey PRIMARY KEY (id);


--
-- Name: licitacion_ofertas licitacion_ofertas_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.licitacion_ofertas
    ADD CONSTRAINT licitacion_ofertas_pkey PRIMARY KEY (id);


--
-- Name: licitaciones_seleccion licitaciones_seleccion_codigo_licitacion_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.licitaciones_seleccion
    ADD CONSTRAINT licitaciones_seleccion_codigo_licitacion_key UNIQUE (codigo_licitacion);


--
-- Name: licitaciones_seleccion licitaciones_seleccion_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.licitaciones_seleccion
    ADD CONSTRAINT licitaciones_seleccion_pkey PRIMARY KEY (id);


--
-- Name: lista_valores lista_valores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lista_valores
    ADD CONSTRAINT lista_valores_pkey PRIMARY KEY (id);


--
-- Name: logs_auditoria logs_auditoria_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.logs_auditoria
    ADD CONSTRAINT logs_auditoria_pkey PRIMARY KEY (id);


--
-- Name: miembros_comite miembros_comite_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.miembros_comite
    ADD CONSTRAINT miembros_comite_pkey PRIMARY KEY (id);


--
-- Name: notificaciones_proveedor notificaciones_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones_proveedor
    ADD CONSTRAINT notificaciones_proveedor_pkey PRIMARY KEY (id);


--
-- Name: ordenes_compra ordenes_compra_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_codigo_key UNIQUE (codigo);


--
-- Name: ordenes_compra_items ordenes_compra_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordenes_compra_items
    ADD CONSTRAINT ordenes_compra_items_pkey PRIMARY KEY (id);


--
-- Name: ordenes_compra ordenes_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_pkey PRIMARY KEY (id);


--
-- Name: pagos_liquidados pagos_liquidados_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos_liquidados
    ADD CONSTRAINT pagos_liquidados_pkey PRIMARY KEY (id);


--
-- Name: pagos_liquidados pagos_liquidados_referencia_pago_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos_liquidados
    ADD CONSTRAINT pagos_liquidados_referencia_pago_key UNIQUE (referencia_pago);


--
-- Name: pagos pagos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_pkey PRIMARY KEY (id);


--
-- Name: pagos pagos_referencia_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_referencia_key UNIQUE (referencia);


--
-- Name: parametros_base parametros_base_clave_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametros_base
    ADD CONSTRAINT parametros_base_clave_key UNIQUE (clave);


--
-- Name: parametros_base parametros_base_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.parametros_base
    ADD CONSTRAINT parametros_base_pkey PRIMARY KEY (id);


--
-- Name: partidas_presupuestarias partidas_presupuestarias_codigo_partida_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidas_presupuestarias
    ADD CONSTRAINT partidas_presupuestarias_codigo_partida_key UNIQUE (codigo_partida);


--
-- Name: partidas_presupuestarias partidas_presupuestarias_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.partidas_presupuestarias
    ADD CONSTRAINT partidas_presupuestarias_pkey PRIMARY KEY (id);


--
-- Name: presupuesto_modificaciones presupuesto_modificaciones_codigo_modificacion_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.presupuesto_modificaciones
    ADD CONSTRAINT presupuesto_modificaciones_codigo_modificacion_key UNIQUE (codigo_modificacion);


--
-- Name: presupuesto_modificaciones presupuesto_modificaciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.presupuesto_modificaciones
    ADD CONSTRAINT presupuesto_modificaciones_pkey PRIMARY KEY (id);


--
-- Name: presupuesto_trazabilidad presupuesto_trazabilidad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.presupuesto_trazabilidad
    ADD CONSTRAINT presupuesto_trazabilidad_pkey PRIMARY KEY (id);


--
-- Name: presupuestos presupuestos_codigo_partida_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.presupuestos
    ADD CONSTRAINT presupuestos_codigo_partida_key UNIQUE (codigo_partida);


--
-- Name: presupuestos presupuestos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.presupuestos
    ADD CONSTRAINT presupuestos_pkey PRIMARY KEY (id);


--
-- Name: proveedores proveedores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT proveedores_pkey PRIMARY KEY (id);


--
-- Name: proveedores proveedores_rif_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.proveedores
    ADD CONSTRAINT proveedores_rif_key UNIQUE (rif);


--
-- Name: recepciones_almacen recepciones_almacen_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recepciones_almacen
    ADD CONSTRAINT recepciones_almacen_codigo_key UNIQUE (codigo);


--
-- Name: recepciones_almacen_items recepciones_almacen_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recepciones_almacen_items
    ADD CONSTRAINT recepciones_almacen_items_pkey PRIMARY KEY (id);


--
-- Name: recepciones_almacen recepciones_almacen_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recepciones_almacen
    ADD CONSTRAINT recepciones_almacen_pkey PRIMARY KEY (id);


--
-- Name: rendicion_gastos rendicion_gastos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rendicion_gastos
    ADD CONSTRAINT rendicion_gastos_pkey PRIMARY KEY (id);


--
-- Name: requerimientos requerimientos_codigo_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requerimientos
    ADD CONSTRAINT requerimientos_codigo_key UNIQUE (codigo);


--
-- Name: requerimientos requerimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.requerimientos
    ADD CONSTRAINT requerimientos_pkey PRIMARY KEY (id);


--
-- Name: retenciones retenciones_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retenciones
    ADD CONSTRAINT retenciones_pkey PRIMARY KEY (id);


--
-- Name: roles roles_nombre_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_nombre_key UNIQUE (nombre);


--
-- Name: roles roles_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roles
    ADD CONSTRAINT roles_pkey PRIMARY KEY (id);


--
-- Name: solicitudes_compra solicitudes_compra_codigo_solicitud_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitudes_compra
    ADD CONSTRAINT solicitudes_compra_codigo_solicitud_key UNIQUE (codigo_solicitud);


--
-- Name: solicitudes_compra solicitudes_compra_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitudes_compra
    ADD CONSTRAINT solicitudes_compra_pkey PRIMARY KEY (id);


--
-- Name: solicitudes_ingreso_proveedor solicitudes_ingreso_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitudes_ingreso_proveedor
    ADD CONSTRAINT solicitudes_ingreso_proveedor_pkey PRIMARY KEY (id);


--
-- Name: solicitudes_proveedor solicitudes_proveedor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitudes_proveedor
    ADD CONSTRAINT solicitudes_proveedor_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: usuarios usuarios_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_username_key UNIQUE (username);


--
-- Name: viaticos_movimientos viaticos_movimientos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaticos_movimientos
    ADD CONSTRAINT viaticos_movimientos_pkey PRIMARY KEY (id);


--
-- Name: viaticos_parametros viaticos_parametros_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaticos_parametros
    ADD CONSTRAINT viaticos_parametros_pkey PRIMARY KEY (id);


--
-- Name: viaticos viaticos_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaticos
    ADD CONSTRAINT viaticos_pkey PRIMARY KEY (id);


--
-- Name: viaticos_soportes viaticos_soportes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaticos_soportes
    ADD CONSTRAINT viaticos_soportes_pkey PRIMARY KEY (id);


--
-- Name: caja_chica_soportes caja_chica_soportes_movimiento_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.caja_chica_soportes
    ADD CONSTRAINT caja_chica_soportes_movimiento_id_fkey FOREIGN KEY (movimiento_id) REFERENCES public.caja_chica_movimientos(id) ON DELETE CASCADE;


--
-- Name: casos_comite casos_comite_comite_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.casos_comite
    ADD CONSTRAINT casos_comite_comite_id_fkey FOREIGN KEY (comite_id) REFERENCES public.comites(id) ON DELETE CASCADE;


--
-- Name: cxp cxp_orden_compra_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cxp
    ADD CONSTRAINT cxp_orden_compra_id_fkey FOREIGN KEY (orden_compra_id) REFERENCES public.ordenes_compra(id) ON DELETE SET NULL;


--
-- Name: cxp cxp_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cxp
    ADD CONSTRAINT cxp_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE SET NULL;


--
-- Name: cxp cxp_recepcion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cxp
    ADD CONSTRAINT cxp_recepcion_id_fkey FOREIGN KEY (recepcion_id) REFERENCES public.recepciones_almacen(id) ON DELETE SET NULL;


--
-- Name: documentacion_proveedor documentacion_proveedor_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentacion_proveedor
    ADD CONSTRAINT documentacion_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE CASCADE;


--
-- Name: documentos_proveedor documentos_proveedor_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.documentos_proveedor
    ADD CONSTRAINT documentos_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE CASCADE;


--
-- Name: evaluaciones_proveedor evaluaciones_proveedor_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.evaluaciones_proveedor
    ADD CONSTRAINT evaluaciones_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE CASCADE;


--
-- Name: facturas_cxp facturas_cxp_orden_compra_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas_cxp
    ADD CONSTRAINT facturas_cxp_orden_compra_id_fkey FOREIGN KEY (orden_compra_id) REFERENCES public.ordenes_compra(id) ON DELETE SET NULL;


--
-- Name: facturas_cxp facturas_cxp_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.facturas_cxp
    ADD CONSTRAINT facturas_cxp_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE SET NULL;


--
-- Name: licitacion_ofertas licitacion_ofertas_licitacion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.licitacion_ofertas
    ADD CONSTRAINT licitacion_ofertas_licitacion_id_fkey FOREIGN KEY (licitacion_id) REFERENCES public.licitaciones_seleccion(id) ON DELETE CASCADE;


--
-- Name: licitacion_ofertas licitacion_ofertas_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.licitacion_ofertas
    ADD CONSTRAINT licitacion_ofertas_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE CASCADE;


--
-- Name: licitaciones_seleccion licitaciones_seleccion_proveedor_ganador_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.licitaciones_seleccion
    ADD CONSTRAINT licitaciones_seleccion_proveedor_ganador_id_fkey FOREIGN KEY (proveedor_ganador_id) REFERENCES public.proveedores(id) ON DELETE SET NULL;


--
-- Name: licitaciones_seleccion licitaciones_seleccion_solicitud_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.licitaciones_seleccion
    ADD CONSTRAINT licitaciones_seleccion_solicitud_id_fkey FOREIGN KEY (solicitud_id) REFERENCES public.solicitudes_compra(id) ON DELETE SET NULL;


--
-- Name: miembros_comite miembros_comite_comite_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.miembros_comite
    ADD CONSTRAINT miembros_comite_comite_id_fkey FOREIGN KEY (comite_id) REFERENCES public.comites(id) ON DELETE CASCADE;


--
-- Name: notificaciones_proveedor notificaciones_proveedor_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notificaciones_proveedor
    ADD CONSTRAINT notificaciones_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE CASCADE;


--
-- Name: ordenes_compra_items ordenes_compra_items_oc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordenes_compra_items
    ADD CONSTRAINT ordenes_compra_items_oc_id_fkey FOREIGN KEY (oc_id) REFERENCES public.ordenes_compra(id) ON DELETE CASCADE;


--
-- Name: ordenes_compra ordenes_compra_licitacion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_licitacion_id_fkey FOREIGN KEY (licitacion_id) REFERENCES public.licitaciones_seleccion(id) ON DELETE SET NULL;


--
-- Name: ordenes_compra ordenes_compra_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.ordenes_compra
    ADD CONSTRAINT ordenes_compra_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE SET NULL;


--
-- Name: pagos pagos_cxp_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_cxp_id_fkey FOREIGN KEY (cxp_id) REFERENCES public.cxp(id) ON DELETE SET NULL;


--
-- Name: pagos pagos_factura_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES public.cxp(id) ON DELETE SET NULL;


--
-- Name: pagos_liquidados pagos_liquidados_factura_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos_liquidados
    ADD CONSTRAINT pagos_liquidados_factura_id_fkey FOREIGN KEY (factura_id) REFERENCES public.facturas_cxp(id) ON DELETE SET NULL;


--
-- Name: pagos_liquidados pagos_liquidados_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos_liquidados
    ADD CONSTRAINT pagos_liquidados_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE SET NULL;


--
-- Name: pagos pagos_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pagos
    ADD CONSTRAINT pagos_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE SET NULL;


--
-- Name: presupuesto_trazabilidad presupuesto_trazabilidad_partida_codigo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.presupuesto_trazabilidad
    ADD CONSTRAINT presupuesto_trazabilidad_partida_codigo_fkey FOREIGN KEY (partida_codigo) REFERENCES public.partidas_presupuestarias(codigo_partida);


--
-- Name: recepciones_almacen_items recepciones_almacen_items_recepcion_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recepciones_almacen_items
    ADD CONSTRAINT recepciones_almacen_items_recepcion_id_fkey FOREIGN KEY (recepcion_id) REFERENCES public.recepciones_almacen(id) ON DELETE CASCADE;


--
-- Name: recepciones_almacen recepciones_almacen_oc_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.recepciones_almacen
    ADD CONSTRAINT recepciones_almacen_oc_id_fkey FOREIGN KEY (oc_id) REFERENCES public.ordenes_compra(id) ON DELETE SET NULL;


--
-- Name: rendicion_gastos rendicion_gastos_viatico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rendicion_gastos
    ADD CONSTRAINT rendicion_gastos_viatico_id_fkey FOREIGN KEY (viatico_id) REFERENCES public.viaticos(id) ON DELETE CASCADE;


--
-- Name: retenciones retenciones_cxp_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.retenciones
    ADD CONSTRAINT retenciones_cxp_id_fkey FOREIGN KEY (cxp_id) REFERENCES public.cxp(id) ON DELETE CASCADE;


--
-- Name: solicitudes_compra solicitudes_compra_partida_codigo_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitudes_compra
    ADD CONSTRAINT solicitudes_compra_partida_codigo_fkey FOREIGN KEY (partida_codigo) REFERENCES public.partidas_presupuestarias(codigo_partida);


--
-- Name: solicitudes_proveedor solicitudes_proveedor_proveedor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.solicitudes_proveedor
    ADD CONSTRAINT solicitudes_proveedor_proveedor_id_fkey FOREIGN KEY (proveedor_id) REFERENCES public.proveedores(id) ON DELETE SET NULL;


--
-- Name: usuarios usuarios_role_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_role_id_fkey FOREIGN KEY (role_id) REFERENCES public.roles(id) ON DELETE SET NULL;


--
-- Name: viaticos_movimientos viaticos_movimientos_viatico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaticos_movimientos
    ADD CONSTRAINT viaticos_movimientos_viatico_id_fkey FOREIGN KEY (viatico_id) REFERENCES public.viaticos(id) ON DELETE CASCADE;


--
-- Name: viaticos_soportes viaticos_soportes_viatico_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.viaticos_soportes
    ADD CONSTRAINT viaticos_soportes_viatico_id_fkey FOREIGN KEY (viatico_id) REFERENCES public.viaticos(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict pZ2T2h4IX3mhJ1qmiP69vLcaCSs52orXofoDsV8ZWtyMMNOmdqgZa2yMcG3udwI

